version: 2
jobs:
  build_py3:
    docker:
      - image: pshriwise/pshriwise:ubuntu_17.04_pymoab_pyne

    working_directory: ~/repo

    steps:
      - checkout

      # Build!
      - run:
          name: Building PyNE
          command: |
            python3 setup.py install --user \
                --moab $HOME/opt/moab --dagmc $HOME/opt/dagmc --clean

      # Test!
      - run:
          name: Running PyNE Tests
          command: |
            cd ~/repo/tests
            ./travis-run-tests.sh python3

  build_py2:
    docker:
      - image: pshriwise/pshriwise:ubuntu_16.04_pymoab_pyne

    working_directory: ~/repo

    steps:
      - checkout

      # Build!
      - run:
          name: Building PyNE
          command: |
            python setup.py install --user \
                --moab $HOME/opt/moab --dagmc $HOME/opt/dagmc--clean

      # Test!
      - run:
          name: Running PyNE Tests
          command: |
            cd ~/repo/tests
            ./travis-run-tests.sh python2


workflows:
  version: 2
  build_and_test:
    jobs:
      - build_py2
      - build_py3
